### ISSUE TITLE
언제, 어떻게 알람이 울리도록 구현할 것인지

### ISSUE THREAD

**Issue by dhmonoxide** [ProjectInTheClass/ExpCatcher#10]
- 설정창을 따로 두어 설정할 수 있게 할지, 아니면 다른 방법을 활용할 것인지 고민할 것
- 현재 iOS 캘린더에서 구현되고 있는 알람을 참고할 것

**Comment by lucid2713** [comment]
아직 찾아보는 중이고... 내일중으로 아이디어 정리해서 다시 답글달게요! 
* 디자인 : 스케줄 관련앱들 + 알림설정 

https://kr.pinterest.com/evenemento/schedule-agenda-ui/
http://www.imore.com/best-reminder-task-apps-iphone
http://pttrns.com/iphone-patterns?scid=35
http://pttrns.com/applications/532
http://pttrns.com/iphone-patterns?scid=4

* 코딩 구현 : local notification 

https://soulpark.wordpress.com/2013/01/15/ios-local-notifications/
http://avilos.codes/mobile/ios-swift/ios-swift-%EB%A1%9C%EC%BB%AC%EC%95%8C%EB%A6%BClocal-notification/
https://www.hackingwithswift.com/read/21/2/scheduling-notifications-unusernotificationcenter-and-unnotificationrequest
http://www.ioscreator.com/tutorials/local-notification-tutorial-ios8-swift
https://www.youtube.com/watch?v=9Xmm15dq3dA
